# Add configuration values here, as shown below.
pusher_app_id: "152687"
pusher_key: "9a29dc21625531215e18"
pusher_secret: "b07b3be6f2f24a87c5de"

S3_KEY: "AKIAIHJORRI42G66WM4A"
S3_SECRET: "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"
S3_BUCKET_NAME: "evntlr"

# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
