# # Add configuration values here, as shown below.
# pusher_app_id: '152687'
# pusher_key: '9a29dc21625531215e18'
# pusher_secret: 'b07b3be6f2f24a87c5de'
#
# production:
#   pusher_app_id: '156802'
#   pusher_key: '0cdf7561a0fb9a4dcab5'
#   pusher_secret: '8dc7c2b522e3b8789086'
