# Add configuration values here, as shown below.
pusher_app_id: "152687"
pusher_key: "9a29dc21625531215e18"
pusher_secret: "b07b3be6f2f24a87c5de"


S3_KEY: "AKIAJJH0L57QJJ5VLTBQ"
S3_SECRET: "XHyfr6cVTd2GudFqYoN90MERb3BodLKgdVHtheqh"
S3_BUCKET_NAME: "evntlr"
S3_REGION: "us-west-2"

# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
